/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lambdaworks_crypto_SCrypt */

#ifndef _Included_com_lambdaworks_crypto_SCrypt
#define _Included_com_lambdaworks_crypto_SCrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lambdaworks_crypto_SCrypt
 * Method:    scryptN
 * Signature: ([B[BIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_lambdaworks_crypto_SCrypt_scryptN
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
